# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

gems:
  - jekyll-feed
#  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - "/vendor/"
  - Gemfile
  - Gemfile.lock

title: L-Cafe
subtitle: Software, infosec, system administration projects, opinions and tips.
email: L-Cafe@linux.com
description: > # this means to ignore newlines until "baseurl:"
  Keep your eyes on the stars, and your feet on the ground. - Theodore Roosevelt
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://l-cafe.github.io"
cover: "/media/header_image.jpg"
logo: "/media/logo.png"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"

social:
  - name: Twitter
    icon: twitter
    username: L__Cafe
    url: https://twitter.com/L__Cafe
    desc: Follow me on Twitter
    share: true

  - name: Facebook
    icon: facebook
    username:
    url:
    desc: Friend me on Facebook
    share: true

  - name: GitHub
    icon: github
    username: L-Cafe
    url: https://github.com/L-Cafe
    desc: Follow me on GitHub
    share: false 

  - name: LinkedIn
    icon: linkedin
    username:
    url: 
    desc: Connect with me on LinkedIn
    share: true

  - name: Google+
    icon: google-plus
    username:
    url:
    desc: Add me to your Circles
    share: true

#  - name: YouTube
#    icon: youtube
#    username:
#    url:
#    desc: Subscribe on YouTube
#    share: false

#  - name: Instagram
#    icon: instagram
#    username:
#    url:
#    desc: Follow me on Instagram
#    share: false

  - name: Pinterest
    icon: pinterest
    username:
    url:
    desc: Follow me on Pinterest
    share: true

  - name: SoundCloud
    icon: soundcloud
    username: L-Cafe
    url: https://soundcloud.com/l_cafe
    desc: Follow me on SoundCloud
    share: false

  - name: Tumblr
    icon: tumblr
    username:
    url:
    desc: Follow me on Tumblr
    share: true

#  - name: Steam
#    icon: steam
#    username:
#    url:
#    desc: Friend me on Steam
#    share: false

#  - name: Vimeo
#    icon: vimeo-square
#    username:
#    url:
#    desc: Follow me on Vimeo
#    share: false

  - name: Reddit
    icon: reddit
    username:
    url:
    desc: Share to Reddit
    share: true

  - name: "Hacker News"
    icon: hacker-news
    username: #Hakashiro # Commented because Karma is below 2 and API is not available
    url: #https://news.ycombinator.com/user?id=Hakashiro
    desc: Share to Hacker News
    share: true


#protocols:
#    fb_image: "/assets/logo.png"
#    fb_image_width: 612
#    fb_image_height: 605
#    fb_image_type: "image/png"
#
#    twitter_image: "/assets/logo.png"
#
#    os_repo: "https://github.com/xxx/yyy"
#    os_rcs_type: "git"
#    os_src: "git@github.com:user/repo.git"
